// Generated by gencpp from file com760_Suhael_Ahmed/b00856266LeaderInstruction.msg
// DO NOT EDIT!


#ifndef COM760_SUHAEL_AHMED_MESSAGE_B00856266LEADERINSTRUCTION_H
#define COM760_SUHAEL_AHMED_MESSAGE_B00856266LEADERINSTRUCTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com760_Suhael_Ahmed
{
template <class ContainerAllocator>
struct b00856266LeaderInstruction_
{
  typedef b00856266LeaderInstruction_<ContainerAllocator> Type;

  b00856266LeaderInstruction_()
    : instructionID(0)
    , message()  {
    }
  b00856266LeaderInstruction_(const ContainerAllocator& _alloc)
    : instructionID(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _instructionID_type;
  _instructionID_type instructionID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> const> ConstPtr;

}; // struct b00856266LeaderInstruction_

typedef ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<std::allocator<void> > b00856266LeaderInstruction;

typedef boost::shared_ptr< ::com760_Suhael_Ahmed::b00856266LeaderInstruction > b00856266LeaderInstructionPtr;
typedef boost::shared_ptr< ::com760_Suhael_Ahmed::b00856266LeaderInstruction const> b00856266LeaderInstructionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace com760_Suhael_Ahmed

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'com760_Suhael_Ahmed': ['/home/andre/Desktop/Untitled Folder/src/com760_Suhael_Ahmed/src/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0322711d40d955a41c13dde39236d522";
  }

  static const char* value(const ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0322711d40d955a4ULL;
  static const uint64_t static_value2 = 0x1c13dde39236d522ULL;
};

template<class ContainerAllocator>
struct DataType< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com760_Suhael_Ahmed/b00856266LeaderInstruction";
  }

  static const char* value(const ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 instructionID\n\
string message\n\
";
  }

  static const char* value(const ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.instructionID);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct b00856266LeaderInstruction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com760_Suhael_Ahmed::b00856266LeaderInstruction_<ContainerAllocator>& v)
  {
    s << indent << "instructionID: ";
    Printer<int64_t>::stream(s, indent + "  ", v.instructionID);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM760_SUHAEL_AHMED_MESSAGE_B00856266LEADERINSTRUCTION_H
